### ISSUE TITLE
Addon fails to register to TST occasionally.

### ISSUE THREAD

**Issue by gabri25ele** [joshuacant/tst_open_in_private#1]
I installed the TST open in private
https://i.imgur.com/qxlXepZ.png

but I don't see any command to open
https://i.imgur.com/ZoxIKml.png

**Comment by joshuacant** [comment]
That's odd. Have you tried closing and reopening Firefox? There are some intermittent issues I've been having with my addons connecting to TST. The option "Open Tab in Private Window" should appear right below where it says "Tree Style Tab  >" in the menu.

Let me know if the issue continues after a restart of Firefox.

**Comment by gabri25ele** [comment]
now it works :)
