### ISSUE TITLE
Update the description on the Firefox Addons page

### ISSUE THREAD

**Issue by Trixlight** [joshuacant/tst_open_in_private#2]
"_You need to allow this extension to Run in Private Windows, otherwise it won't work._"

Something like this.

**Comment by joshuacant** [comment]
It's my own extension, so I always granted it that permission. This must be why I have all those negative reviews claiming it doesn't work at all, when it clearly does (for me!)

Thanks for actually letting me know, I'll add some text to the addon page and hopefully people read it.
